### ISSUE TITLE
SKOS tipos de calle: circunvalación

### ISSUE THREAD

**Issue by jcballesteros** [opencitydata/listas-codigos-skos#12]
En el ttl: https://github.com/opencitydata/listas-codigos-skos/blob/master/urbanismo-infraestructuras/callejero/TipoViasINE.ttl

El pref label de circunvalación es incorrecto:

skos:prefLabel "CIRCUMVAL.LACIO" ;

**Comment by ocorcho** [comment]
Se trata de un prefLabel que procede del término en catalán, según está descrito en el fichero original del INE.
