### ISSUE TITLE
Cambios en SKOS de Tipos de Eventos (Agenda Municipal)

### ISSUE THREAD

**Issue by paoespinozarias** [opencitydata/listas-codigos-skos#14]
Tras la reunión celebrada con los ayuntamientos para la validación del vocabulario de [Agenda Municipal](https://github.com/opencitydata/sector-publico-agenda-municipal) se solicitan los siguientes cambios en el SKOS [tipo-evento](https://github.com/opencitydata/listas-codigos-skos/blob/master/sector-publico/agenda-municipal/tipo-evento/tipo-evento.ttl)

- Renombrar _Reunión Órganos Colegiados_ por _Sesión Órganos Colegiados_.
- Renombrar los conceptos _Comisión Plenaria Ordinaria Permanente_ y _Comisión Plenaria Ordinaria No Permanente_  por _Comisión Permanente_ y _Comisión No Permanente_. Clasificar ambos conceptos como un subconcepto de _Reunión Órganos Colegiados_.
- Remover el concepto _Comisión Plenaria_.
- Remover el concepto _Comisión Plenaria Especial_ porque puede formar parte ya sea de las _Comisiones Permanentes_ o de las _Comisiones No Permanentes_. Por lo tanto, cada ayuntamiento tendrá que interpretar según la naturaleza de la comisión que requiera clasificar con cual de los dos conceptos encajaría.
- Renombrar el concepto _Reunión Grupo Político_ por _Reunión de Grupo Político_ y clasificarlo como un subconcepto de _Otras Reuniones_ en lugar de un subconcepto de _Reunión Órganos Colegiados_.
- Renombrar el concepto _Reunión con Personas_ por _Reunión con Ciudadanía_.
- Renombrar el concepto _Reunión con Medios de Comunicación_ por _Evento con Medio de Comunicación_.

Finalmente, hay que revisar algunos de los skos:prefLabel de este SKOS pues hay que agregarles el idioma ("@es") y retocar los labels asignados.

**Comment by ednaru** [comment]
Se realizaron los cambios.
