### ISSUE TITLE
Incluir los skos de convenios en este espacio

### ISSUE THREAD

**Issue by runobe** [opencitydata/listas-codigos-skos#17]
Hola, no se deberían de incluir los skos definidos para el vocabulario de convenios en este espacio?

**Comment by ocorcho** [comment]
Sí, se incluirán una vez acordados

**Comment by ednaru** [comment]
Los skos de tipo de entidad, modalidad y tipo de convenio están publicados en: https://github.com/opencitydata/listas-codigos-skos/tree/master/sector-publico/convenio.
El de materia (programa de gasto) está aquí:
https://github.com/opencitydata/listas-codigos-skos/tree/master/hacienda/presupuesto/programa-gasto

**Comment by runobe** [comment]
ok, gracias
