### ISSUE TITLE
Términos de tipo-entidad en convenio - Otras organizaciones de carácter privado

### ISSUE THREAD

**Issue by ednaru** [opencitydata/listas-codigos-skos#20]
En https://github.com/opencitydata/listas-codigos-skos/tree/master/sector-publico/convenio/tipo-entidad A Coruña solicita agregar la definición en el SKOS del término "Otras organizaciones de carácter privado".

**Comment by ednaru** [comment]
@H-EnriqueCrespo, @arribasamm, @innovacion-santiago, @runobe pueden proponer una definición.

**Comment by runobe** [comment]
Ese término desde Zaragoza lo vemos como un elemento comodín en el caso de que la entidad no tenga cabida en algún término anterior bien por desconocimiento o por que su actividad no coincida con las que ya figuran (deporte,financiera..).
Dicho lo anterior la definición formal podría ser del tipo: "Aquellas organizaciones de carácter privado que se desconozca su tipo o no coincida con alguna de las ya existentes"

**Comment by ednaru** [comment]
@runobe, parece una definición apropiada. Se agrega al SKOS de tipo de entidad

**Comment by ednaru** [comment]
Se ha agregado esta definición en la nueva versión del SKOS.

**Comment by ednaru** [comment]
Se ha agregado esta definición en la nueva versión del SKOS.
