### ISSUE TITLE
Cambio en clasificación de términos para materia de convenio

### ISSUE THREAD

**Issue by ednaru** [opencitydata/listas-codigos-skos#24]
En https://github.com/opencitydata/listas-codigos-skos/tree/master/hacienda/presupuesto/programa-gasto
está la clasificación. Se propuso originalmente utilizar la clasificación de presupuestos de programas de gasto con dos niveles: área de gasto y política de gasto.
A Coruña @corunaes propone utilizar BDNS con  dos clasificaciones
1.- Sector económico, código NACE. Se utiliza en la BDNS para clasificar al beneficiario de una subvención. La BDNS utiliza la Nomenclatura estadística de actividades económicas de la Comunidad Europea (NACE) es el sistema de clasificación de las actividades económicas usado en la Unión Europea. Sirve para la organización y el registro de datos en el marco de Eurostat, la base de datos estadísticos comunitaria, así como para las estadísticas oficiales de cada Estado miembro. Su uso es obligatorio para los datos que se deben mostrar por transparencia o enviar a los órganos competentes de la UE. Por razones lógicas, a la hora de categorizar a los beneficiarios de ayudas y subvenciones, se opta por emplear esta nomenclatura en toda la BDNS. El INE dispone de un documento metodológico cuya consulta puede resolver muchas dudas en inquietudes sobre esta tabla: http://www.ine.es/daco/daco42/clasificaciones/cnae09/notas.pdf
Aunque la tabla se desarrolla al nivel “clase” (5 dígitos), los Reglamentos de la Comisión EU 651/2014 EU 702/2014 y EU 1388/2014 sólo obligan a registrar la información al nivel “grupo” (4 dígitos), siendo éste el nivel de desarrollo establecido en la BDNS.
La correspondencia entre las tablas NACE Rev.2 con CNAE-2009 se puede localizar en:
http://www.ine.es/daco/daco42/clasificaciones/cnae09/cnae_2009_rd.pdf

2.- La finalidad de la subvención

 Se clasifica según cuál sea la finalidad de la subvención:
·         Acceso a la vivienda
·         Agricultura, pesca y alimentación
·         Comercio, Turismo y Pymes
·         Comercio internacional para el desarrollo y cultural
·         Cultura
·         Defensa
·         Desempleo
·         Educación
·         Fomento del Empleo
·         Industria y Energía
·         Infraestructuras
·         Investigación, desarrollo e innovación
·         Justicia
·         Otras prestaciones económicas
·         Otras actuaciones de carácter económico
.         Sanidad 
·         Seguridad ciudadana e instituciones penitenciarias
·         Servicios sociales y Promoción social
·         Subvenciones al transporte

**Comment by ednaru** [comment]
@H-EnriqueCrespo, @arribasamm, @innovacion-santiago, @runobe pueden revisar esta issue. Debemos tomar una decisión sobre cuál taxonomía adoptar.

**Comment by runobe** [comment]
En principio nosotros como tenemos que crear un sistema de gestión de convenios nos adecuaremos a lo que se decida aquí igual nos da generar una clasificación u otra pero pensando en los gestores de convenios desde Zaragoza nos surgen varias dudas/reflexiones:
1) No todos los convenios surgen de subvenciones y no sabemos si en ese caso puede ser excesivo para quien cumplimente el dato el obtener el código NACE, entendemos que el determinarlo por la materia de subvención a priori no es complicado ya que tiene bastante similitud con respecto a la política de gasto
2) Al no seguir la clasificación de gasto igual estamos perdiendo una posible relación directa con otros datasets que nos permitiría relacionarlos de manera fácil pero bueno a una mala en caso de querer hacer esto siempre podríamos establecer relaciones entre ambas clasificaciones.

**Comment by ednaru** [comment]
El experto de A Coruña comenta que comparte totalmente el argumento de que no todos los convenios son subvenciones. Es más, incluso el hecho de que lleven fijada una cuantía económica implica que todos ellos sean subvenciones. 
La idea que propuesieron respecto de los códigos NACE era por unificar un criterio que todos durante la tramitación de subvenciones ya vienen utilizando, lo que en principio parecía podría ayudar a responder uniformemente lo que se refiere a la clasificación.

Con todo, cree que no supone problema alguno la clasificación según programas de gasto, también por todos utilizado. Con ello quiere decir que no supone dificultad ninguna adoptar esa clasificación en la taxonomía de los convenios.

**Comment by ednaru** [comment]
De acuerdo al último comentario se decide mantener la clasificación por Programa de Gasto como taxonomía para materia de un convenio.
