### ISSUE TITLE
Modificación de URIs para SKOS de tráfico

### ISSUE THREAD

**Issue by ocorcho** [opencitydata/listas-codigos-skos#26]
En los SKOS relacionados con tráfico y disponibles en https://github.com/opencitydata/listas-codigos-skos/tree/master/transporte/trafico se utiliza de manera generalizada, para la representación de los Concept Scheme y también para algunos de sus SKOS concepts, el término tipo-XXX
Por ejemplo, en los tipos de equipo de tráfico se utiliza el Concept Scheme http://vocab.linkeddata.es/datosabiertos/kos/transporte/trafico/tipo-equipo-trafico/, y luego sus dos top concepts son 
http://vocab.linkeddata.es/datosabiertos/kos/transporte/trafico/tipo-equipo-trafico/tipo-equipo-control
y 
http://vocab.linkeddata.es/datosabiertos/kos/transporte/trafico/tipo-equipo-trafico/tipo-dispositivo-medicion.

Estos dos últimos deberían utilizar preferentemente URIs como:
http://vocab.linkeddata.es/datosabiertos/kos/transporte/trafico/tipo-equipo-trafico/equipo-control
y 
http://vocab.linkeddata.es/datosabiertos/kos/transporte/trafico/tipo-equipo-trafico/dispositivo-medicion

**Comment by flowsta** [comment]
https://github.com/opencitydata/listas-codigos-skos/commit/15e51bd6b47efd6092cdc7efbda00f3cdd4485e1
