### ISSUE TITLE
Error en el kos organizacion/tipo-entidad.ttl 

### ISSUE THREAD

**Issue by hlafuente** [opencitydata/listas-codigos-skos#9]
En el kos listas-codigos-skos/sector-publico/organizacion/tipo-entidad.ttl, hay un trozo de código para el kos de empresa que es asi:

> <http://vocab.linkeddata.es/datosabiertos/kos/sector-publico/organizacion/tipo-entidad/CO> a skos:Concept ;
>     skos:prefLabel "Empresa"@es ;
>     skos:notation "CO" ;
> skos:inScheme <http://vocab.linkeddata.es/datosabiertos/kos/sector-publico/organizacion/tipo-entidad> .

La notación 'CO' ya se usa para comarca, tiene toda la pinta que debería de ser EM, siguiendo la lógica del resto de kos.

Un saludo.

**Comment by ocorcho** [comment]
Corregido en el commit 18b0134c8b16f758cde3a14477b9870d34f7bb8b , donde se han añadido nuevos tipos de entidades que aparecen en el catálogo de tipos de entidades de DIR3 (https://administracionelectronica.gob.es/ctt/dir3/descargas)

Como ha habido un cambio en un SKOS, @ma-garcia debe hacer la carga de nuevo, borrando los SKOS antiguos (o al menos este SKOS - https://github.com/opencitydata/listas-codigos-skos/blob/master/sector-publico/organizacion/tipo-entidad.ttl) para que estén publicados correctamente.

**Comment by ma-garcia** [comment]
Datos cargados correctamente.
